### ISSUE TITLE
Noise on gba-niccc

### ISSUE THREAD

**Issue by GValiente** [nba-emu/NanoBoyAdvance#141]
NanoBoyAdvance 1.3 shows some noise on [gba-niccc](https://github.com/GValiente/gba-niccc) demo:

![NBA](https://user-images.githubusercontent.com/13147012/107130947-d0c62700-68d2-11eb-9a01-34d62ad677bf.png)

It is difficult to catch it on a screenshot, running the demo shows it better.

It didn't happen with 1.2 release.

**Comment by fleroviux** [comment]
Regression from this commit: https://github.com/fleroviux/NanoboyAdvance/commit/92779c876f287530372b355044e8f9ca8dbf5c8c

Ugh, will have to do some more investigation how this is supposed to work.

**Comment by fleroviux** [comment]
Seems like HDMA runs long enough to overlap with the H-draw period of the next scanline.
Because NBA currently renders the whole scanline at the start of H-draw, it uses old settings for all OAMs that haven't been updated at the start of H-draw yet.

Probably works on hardware because OAM rendering isn't instantaneous and the higher entries in OAM are rendered later.

One fix might be to render OAM at the end of H-draw, but neither way it is really accurate. I guess this means I should finally implement a (sort of) cycle-accurate PPU for real.

**Comment by GValiente** [comment]
Don't know if it helps, but Varooom 3D (https://gvaliente.itch.io/varooom-3d) shows similar issues with much less sprites rendered with HDMA:
![varooom_3d](https://user-images.githubusercontent.com/13147012/172995789-6d9635a9-3f37-4f56-ae07-8394d4010eae.png)
