### ISSUE TITLE
"Hold fast forward key" option does not affect controller

### ISSUE THREAD

**Issue by testyourmine** [nba-emu/NanoBoyAdvance#192]
Apologies if this is an intended feature rather than a bug, but the "Hold fast forward key" option doesn't appear to have any affect on controller. The option works as intended for keyboard, but when I use my Switch Pro Controller connected over Bluetooth (and using no external programs), fast forward only works by pressing (and releasing) the fast forward button (which by default is the "X" button on the controller). It works as a toggle, pressing X enables fast forward and pressing it again disables fast forward. This behavior persists whether or not "Hold fast forward key" is enabled. If this isn't a bug, then it'd be nice to see the option reflect on controller.

**Comment by fleroviux** [comment]
This is the intended behavior, however I'm willing to reconsider. I originally thought that:
1. it's very inconvenient to hold the fast forward key on a controller, while on a keyboard it tends to be the expected behavior. 
2. I  can see that you'd want the "hold" behavior on a keyboard and have the "toggle" behavior on a controller

Maybe then it makes the most sense to split the option for game controller and keyboard?

**Comment by testyourmine** [comment]
I think splitting the option for controller and keyboard would be a good compromise. For me, the reason I want hold to affect controller is
1. I hit the X button on my controller by accident pretty often (well, often enough for it to be annoying), so having hold actually be in affect would help prevent me from suddenly running off the cliff because I accidentally tapped the X button for a split second, and more importantly
2. Often times, I only want to fast forward for a small amount of time (sometimes less than a second), and sometimes in quick intervals (say speeding up several screen transitions in a row), and so I lose track of whether I have fast forward enabled or not.

It's a minor and specific feature, but it'd be appreciated if it's implemented at some point in any form.
