### ISSUE TITLE
Adding missing options to the UI

### ISSUE THREAD

**Issue by RavenMacDaddy** [nba-emu/NanoBoyAdvance#204]
These are the ones that I noticed missing in corresponding section(s) of the UI:

- Sync to audio
- Fast forward (speed)
- Fullscreen hotkey (could possibly go into the remap section)
- Shader (both VS and FS)
- Interpolate FIFO

**Comment by fleroviux** [comment]
Ah, some of these options are from the old SDL2 frontend. But due to how the code is shared between the frontends, they're still written out. Sorry about that.

**Sync-to-audio**
This was a feature of the SDL2 frontend and is not supported in the Qt frontend yet, because there were some technical issues with the current implementation, causing poor performance on some systems.

**Fast forward**
This is actually a key binding and can be found in the input remap dialog.

**Fullscreen hotkey**
This belongs to the SDL2 frontend. In the Qt frontend it is currently hardcoded to Ctrl+F, we should make it configurable though.

**Shader (VS and FS)**
This belongs to the SDL2 frontend. The Qt frontend has a new post-processing stack that allows running multiple passes like upscaling, color correction and interframe blending. But it's not possible to add custom shaders yet.

**Interpolate FIFO**
This option actually works in both frontends, I kind of forgot about exposing it. Sorry about that.

**Comment by RavenMacDaddy** [comment]
No worries, and thanks for your sincere and constructive responses - your work is appreciated.

**Comment by fleroviux** [comment]
At this point the config shouldn't contain any options which aren't exposed to the UI anymore. The Interpolate FIFO option has been removed recently, because it has some issues and wasn't officially supported since a long time.
