### ISSUE TITLE
Disney's Aladdin crashes in-game or in start menu

### ISSUE THREAD

**Issue by petran79** [nba-emu/NanoBoyAdvance#290]
When I launch the game it crashes just 1-2 minutes in the first stage. Sound breaks and loops and picture freezes. Nanoboy works but if I try to load another ROM it crashes.  ROM is from GoodGBA set.

**Comment by fleroviux** [comment]
Can confirm - this seems to be a regression from NBA 1.6.

**Comment by fleroviux** [comment]
I think https://github.com/nba-emu/NanoBoyAdvance/commit/f192f088cd41b352836fbcecc4c18ff3920e9b13 is the commit that broke it.

**Comment by fleroviux** [comment]
Turns out that the commit I previously mentioned did indeed first break this game, but it was not the root cause. The real issue was a threading issue relating to input and the keypad interrupt.

This issue should be fixed in the latest [development build](https://nightly.link/nba-emu/NanoBoyAdvance/workflows/build/master)
