### ISSUE TITLE
Video is not correct in Final Fantasy 1 and 2

### ISSUE THREAD

**Issue by branchus** [nba-emu/NanoBoyAdvance#297]
Windows 11 Pro - NanoBoyAdvance 1.7
Notice the bottom area, the video is not correct.

<img width="959" alt="Screenshot 2023-04-29 104751" src="https://user-images.githubusercontent.com/1289143/235273853-69335bfa-a28c-40f0-93b1-26edf661611c.png">

How to reproduce
start the game, have couple fights, come back to village try to talk to any npc

**Comment by branchus** [comment]
Two more screenshot, seems it can be on bottom as well as on top.
![Screenshot 2023-04-29 143210](https://user-images.githubusercontent.com/1289143/235283548-1d346f31-19f8-49f7-8a2c-b37b9a5acc40.jpg)
![Screenshot 2023-04-29 143249](https://user-images.githubusercontent.com/1289143/235283549-3839ba99-4aa3-4ca6-8eb9-18e5302e252a.jpg)

**Comment by fleroviux** [comment]
This appears to be a regression from NBA 1.6. Most likely related to the PPU rewrite.

**Comment by fleroviux** [comment]
Looks like 1fbe80bbc61d0ade64e80e5f44a0c87e6411b9f7 is the regressing commit.

**Comment by fleroviux** [comment]
This was caused by a really old oversight in my code that somehow was not triggered until this recent change.

If the CPU is halted the code would check if there are any DMAs to execute and then fast-forward in time to the next hardware event. It would then check if the CPU should wake up. However it is possible that the condition for waking up the CPU becomes true during the DMA, which means that still fast-forwarding to the next event is incorrect in that case.

The fix addresses this by checking if the CPU should wake up after executing a DMA and not skipping to the next event in that case.
