### ISSUE TITLE
[Regression] - mGBA Suite Crashes on NBA 1.7

### ISSUE THREAD

**Issue by Zenjir0** [nba-emu/NanoBoyAdvance#301]
When you try to run [endrift](https://github.com/mgba-emu/mgba/commits?author=endrift)'s [gba-suite](https://s3.amazonaws.com/mgba/suite-latest.zip) on NanoBoyAdvance 1.7 some of the test will outright crash the program. 

This behavior is easily replicated by running the latest suite.gba file (suite.gba date modified 3/27/2023) on NBA v1.7 and attempting to run the tests.

However the same suite.gba file runs without issue on all tests for NBA v1.6 and v1.5, and does not crash.

**Comment by fleroviux** [comment]
Weird. I use this test suite regularly for regression testing. That being said it's possible that I missed something. I'll take a look tonight.

**Comment by fleroviux** [comment]
Looks like this crash is connected to the recent implementation of the mGBA logging interface, which `suite.gba` uses to print out test results. The crash does not happen when running NanoBoyAdvance from the console (which is what I do most of the time). It incidentally also does not crash anymore [on the latest commit](https://github.com/nba-emu/NanoBoyAdvance/commit/c657dfbb90e809ca967ad2f08af08d2a36001a4c) which makes sure to flush `stdout` after every log message. 

I wonder if the crash is happens if nothing drains from stdout and its buffer eventually is being overrun.

**Comment by fleroviux** [comment]
Turns out `fmt::print` throws an exception if it fails to write to STDOUT. 
https://github.com/fmtlib/fmt/issues/1176

This is now accounted for by catching and ignoring the exception.

**Comment by Zenjir0** [comment]
Glad to helped and thank you for your contributions to GBA emulation.
