### ISSUE TITLE
Some Famicom Mini titles do not start up.

### ISSUE THREAD

**Issue by KippeiAsakura** [nba-emu/NanoBoyAdvance#302]
Several Japanese Famicom Mini titles do not work on NBA 1.7.

Famicom Mini 23 - Metroid
Famicom Mini 24 - Hikari Shinwa - Palthena no Kagami
Famicom Mini 25 - The Legend of Zelda 2 - Link no Bouken
Famicom Mini 30 - SD Gundam World - Gachapon Senshi Scramble Wars

The above 4 titles will not start.
The remaining titles seem to work fine.
The same ROM will boot with mGBA 0.10.2.

![2023-05-13 235906](https://github.com/nba-emu/NanoBoyAdvance/assets/133012225/fbc6b0ad-1f97-44f3-b27d-3cbe1a96289e)

**Comment by fleroviux** [comment]
Looks like some of the game database entries for save memory were still incorrect. Thanks for the bug report!
I adjusted the game database (and added entries for two games that were missing). It should be fixed in the most recent [development build](https://nightly.link/nba-emu/NanoBoyAdvance/workflows/build/master).
