### ISSUE TITLE
[Feature Request] NS support

### ISSUE THREAD

**Issue by Bossiskeyboard** [nba-emu/NanoBoyAdvance#309]
I would suggest you to make an NS version of this emulator. Since I really like this emulator and would want it on the NS, because I would like to play this emulator on the go.

**Comment by fleroviux** [comment]
Due to the high accuracy this emulator in its current form does not run quickly enough for the Switch's dated hardware.
Given the current trend, this is also not going to get better. A Switch port would probably need to be a hard fork of version 1.6 of the emulator (which in my test, which was a **very** rudimentary/barebones port, was able to run fullspeed).

For now this is not planned though, as it would take away resources from the main emulator.
