### ISSUE TITLE
Unity Boy Advance for Android

### ISSUE THREAD

**Issue by soundsnow** [nba-emu/NanoBoyAdvance#377]
https://youtu.be/N3S11U_t624
This emulator doesn't seem to be available on the Play Store anymore. One more thing, there is no official NBA developed for Android as of yet either. this issue is meant to be a temporary alternative for people using Android devices (especially mobile GBA SP) to find in search engines!

**Comment by fleroviux** [comment]
We're not affiliated with Unity Boy Advance and we don't have any plans to port to Android at the moment either. I don't really get what you mean by "this issue is meant to be a temporary alternative". An open issue for Android support already exists (https://github.com/nba-emu/NanoBoyAdvance/issues/171), therefore I'm closing this.

**Comment by fleroviux** [comment]
> and you've kept them waiting too long!
I'm not payed any money to work on this project, so I don't think I've let anyone waiting "too long". I work on this project when I feel like doing it and when I do there certainly are more important priorities than porting to Android. Unlike the developer of this port I don't have the luxury of focusing only on developing a port.
