### ISSUE TITLE
Metal Max 2 Kai (Japan) flashing text

### ISSUE THREAD

**Issue by benderscruffy** [nba-emu/NanoBoyAdvance#89]
the text keeps flashing during the game

**Comment by fleroviux** [comment]
Can confirm.

**Comment by fleroviux** [comment]
![image](https://user-images.githubusercontent.com/13669774/81995275-2a523b80-964a-11ea-962f-5d5f52ea95fd.png)

Thank you for testing so many games. This one should work fine now.

**Comment by fleroviux** [comment]
The fix for this game actually actually seems to be incorrect and made H-blank IRQs fire too early.
This game is extremely tight on timing. It polls the scanline counter for one specific value/scanline and if the H-blank IRQ is just a bit too late that scanline will already have passed. Needs more investigation. Maybe also related to general IRQ delay?

**Comment by fleroviux** [comment]
The flickering text issue is now finally resolved for good (the fix 100% matches hardware timing).
But there still are a few minor graphical issues left that are unrelated to the original bug.
I've created a new issue here, to track these:
https://github.com/nba-emu/NanoBoyAdvance/issues/229
